# Generated by Django 3.2.9 on 2021-12-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_person_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='surname',
        ),
    ]
